name: Shadow's Lab
url: http://blog.shadowslab.com
description: A site for logging things that I want to remember or find interesting.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

twitter_url: "http://www.twitter.com/aauren"
